PRESETS = {
    "base": "392 61 297",
    "village1": "-1360 70 637",
    "village2": "-3777 63 3823",
    "ice_area": "427 85 -39",
}

VILLAGE_TYPES = [
    "plains",
    "desert",
    "savanna",
    "taiga",
    "snowy"
]

ITEMS = {
    "Food": [
        {"name": "cooked_beef", "display": "Cooked Beef", "icon": "🥩"},
        {"name": "golden_carrot", "display": "Golden Carrot", "icon": "🥕"},
        {"name": "bread", "display": "Bread", "icon": "🍞"},
        {"name": "cooked_porkchop", "display": "Cooked Porkchop", "icon": "🍖"},
        {"name": "cooked_chicken", "display": "Cooked Chicken", "icon": "🍗"},
        {"name": "cooked_mutton", "display": "Cooked Mutton", "icon": "🥩"},
        {"name": "baked_potato", "display": "Baked Potato", "icon": "🥔"},
        {"name": "golden_apple", "display": "Golden Apple", "icon": "🍎"},
        {"name": "enchanted_golden_apple", "display": "God Apple", "icon": "✨"},
        {"name": "cooked_salmon", "display": "Cooked Salmon", "icon": "🐟"},
        {"name": "rabbit_stew", "display": "Rabbit Stew", "icon": "🥣"},
        {"name": "mushroom_stew", "display": "Mushroom Stew", "icon": "🍲"},
        {"name": "pumpkin_pie", "display": "Pumpkin Pie", "icon": "🥧"},
        {"name": "beetroot_soup", "display": "Beetroot Soup", "icon": "🥣"},
    ],
    "Weapons (power coded)": [
        {"name": "netherite_sword", "display": "⬛ Netherite Sword", "icon": "⚔️"},
        {"name": "netherite_axe", "display": "⬛ Netherite Axe", "icon": "🪓"},
        {"name": "netherite_hoe", "display": "⬛ Netherite Hoe (Mace)", "icon": "🪓"},
        {"name": "diamond_sword", "display": "💎 Diamond Sword", "icon": "⚔️"},
        {"name": "diamond_axe", "display": "💎 Diamond Axe", "icon": "🪓"},
        {"name": "diamond_trident", "display": "💎 Trident", "icon": "🔱"},
        {"name": "iron_sword", "display": "⚪ Iron Sword", "icon": "⚔️"},
        {"name": "iron_axe", "display": "⚪ Iron Axe", "icon": "🪓"},
        {"name": "stone_sword", "display": "⬛ Stone Sword", "icon": "⚔️"},
        {"name": "stone_axe", "display": "⬛ Stone Axe", "icon": "🪓"},
        {"name": "golden_sword", "display": "🟡 Golden Sword", "icon": "⚔️"},
        {"name": "golden_axe", "display": "🟡 Golden Axe", "icon": "🪓"},
        {"name": "wooden_sword", "display": "🟤 Wooden Sword", "icon": "⚔️"},
        {"name": "wooden_axe", "display": "🟤 Wooden Axe", "icon": "🪓"},
        {"name": "trident", "display": "💠 Trident", "icon": "🔱"},
        {"name": "crossbow", "display": "🟦 Crossbow", "icon": "🏹"},
        {"name": "bow", "display": "🟩 Bow", "icon": "🏹"},
        {"name": "fire_charge", "display": "🔥 Fire Charge", "icon": "🔥"},
    ],
    "Tools - Netherite": [
        {"name": "netherite_pickaxe", "display": "⬛ Netherite Pickaxe", "icon": "⛏️"},
        {"name": "netherite_axe", "display": "⬛ Netherite Axe", "icon": "🪓"},
        {"name": "netherite_shovel", "display": "⬛ Netherite Shovel", "icon": "🛠️"},
        {"name": "netherite_hoe", "display": "⬛ Netherite Hoe", "icon": "🔧"},
    ],
    "Tools - Diamond": [
        {"name": "diamond_pickaxe", "display": "💎 Diamond Pickaxe", "icon": "⛏️"},
        {"name": "diamond_axe", "display": "💎 Diamond Axe", "icon": "🪓"},
        {"name": "diamond_shovel", "display": "💎 Diamond Shovel", "icon": "🔨"},
        {"name": "diamond_hoe", "display": "💎 Diamond Hoe", "icon": "🔧"},
    ],
    "Tools - Iron": [
        {"name": "iron_pickaxe", "display": "⚪ Iron Pickaxe", "icon": "⛏️"},
        {"name": "iron_axe", "display": "⚪ Iron Axe", "icon": "🪓"},
        {"name": "iron_shovel", "display": "⚪ Iron Shovel", "icon": "🛠️"},
        {"name": "iron_hoe", "display": "⚪ Iron Hoe", "icon": "🔧"},
    ],
    "Tools - Stone": [
        {"name": "stone_pickaxe", "display": "⬛ Stone Pickaxe", "icon": "⛏️"},
        {"name": "stone_axe", "display": "⬛ Stone Axe", "icon": "🪓"},
        {"name": "stone_shovel", "display": "⬛ Stone Shovel", "icon": "🛠️"},
        {"name": "stone_hoe", "display": "⬛ Stone Hoe", "icon": "🔧"},
    ],
    "Tools - Gold": [
        {"name": "golden_pickaxe", "display": "🟡 Golden Pickaxe", "icon": "⛏️"},
        {"name": "golden_axe", "display": "🟡 Golden Axe", "icon": "🪓"},
        {"name": "golden_shovel", "display": "🟡 Golden Shovel", "icon": "🛠️"},
        {"name": "golden_hoe", "display": "🟡 Golden Hoe", "icon": "🔧"},
    ],
    "Tools - Wood": [
        {"name": "wooden_pickaxe", "display": "🟤 Wooden Pickaxe", "icon": "⛏️"},
        {"name": "wooden_axe", "display": "🟤 Wooden Axe", "icon": "🪓"},
        {"name": "wooden_shovel", "display": "🟤 Wooden Shovel", "icon": "🛠️"},
        {"name": "wooden_hoe", "display": "🟤 Wooden Hoe", "icon": "🔧"},
    ],
    "Tools - Utility": [
        {"name": "fishing_rod", "display": "🪝 Fishing Rod", "icon": "🎣"},
        {"name": "shears", "display": "✂️ Shears", "icon": "✂️"},
        {"name": "flint_and_steel", "display": "🔥 Flint and Steel", "icon": "🔥"},
        {"name": "brush", "display": "🪥 Brush", "icon": "🪥"},
    ],
    "Armor": [
        {"name": "diamond_helmet", "display": "Diamond Helmet", "icon": "⛑️"},
        {"name": "diamond_chestplate", "display": "Diamond Chestplate", "icon": "🦺"},
        {"name": "diamond_leggings", "display": "Diamond Leggings", "icon": "👖"},
        {"name": "diamond_boots", "display": "Diamond Boots", "icon": "👢"},
        {"name": "netherite_helmet", "display": "Netherite Helmet", "icon": "⛑️"},
        {"name": "netherite_chestplate", "display": "Netherite Chestplate", "icon": "🦺"},
        {"name": "netherite_leggings", "display": "Netherite Leggings", "icon": "👖"},
        {"name": "netherite_boots", "display": "Netherite Boots", "icon": "👢"},
        {"name": "elytra", "display": "Elytra", "icon": "🪽"},
    ],
    "Building - Wood Core": [
        {"name": "oak_planks", "display": "Oak Planks", "icon": "🪵"},
        {"name": "spruce_planks", "display": "Spruce Planks", "icon": "🪵"},
        {"name": "birch_planks", "display": "Birch Planks", "icon": "🪵"},
        {"name": "dark_oak_planks", "display": "Dark Oak Planks", "icon": "🪵"},
        {"name": "mangrove_planks", "display": "Mangrove Planks", "icon": "🪵"},
        {"name": "bamboo_planks", "display": "Bamboo Planks", "icon": "🪵"},
        {"name": "bamboo_mosaic", "display": "Bamboo Mosaic", "icon": "🟩"},
        {"name": "crimson_planks", "display": "Crimson Planks", "icon": "🪵"},
        {"name": "warped_planks", "display": "Warped Planks", "icon": "🪵"},
        {"name": "oak_log", "display": "Oak Log", "icon": "🪵"},
        {"name": "stripped_oak_log", "display": "Stripped Oak Log", "icon": "🪵"},
        {"name": "cherry_planks", "display": "Cherry Planks", "icon": "🌸"},
        {"name": "cherry_log", "display": "Cherry Log", "icon": "🌸"},
        {"name": "scaffolding", "display": "Scaffolding", "icon": "🪜"},
    ],
    "Building - Wood Stairs & Slabs": [
        {"name": "oak_stairs", "display": "Oak Stairs", "icon": "🪜"},
        {"name": "oak_slab", "display": "Oak Slab", "icon": "➖"},
        {"name": "spruce_stairs", "display": "Spruce Stairs", "icon": "🪜"},
        {"name": "spruce_slab", "display": "Spruce Slab", "icon": "➖"},
        {"name": "birch_stairs", "display": "Birch Stairs", "icon": "🪜"},
        {"name": "birch_slab", "display": "Birch Slab", "icon": "➖"},
        {"name": "dark_oak_stairs", "display": "Dark Oak Stairs", "icon": "🪜"},
        {"name": "dark_oak_slab", "display": "Dark Oak Slab", "icon": "➖"},
        {"name": "mangrove_stairs", "display": "Mangrove Stairs", "icon": "🪜"},
        {"name": "mangrove_slab", "display": "Mangrove Slab", "icon": "➖"},
        {"name": "bamboo_stairs", "display": "Bamboo Stairs", "icon": "🪜"},
        {"name": "bamboo_slab", "display": "Bamboo Slab", "icon": "➖"},
        {"name": "crimson_stairs", "display": "Crimson Stairs", "icon": "🪜"},
        {"name": "crimson_slab", "display": "Crimson Slab", "icon": "➖"},
        {"name": "warped_stairs", "display": "Warped Stairs", "icon": "🪜"},
        {"name": "warped_slab", "display": "Warped Slab", "icon": "➖"},
        {"name": "cherry_stairs", "display": "Cherry Stairs", "icon": "🪜"},
        {"name": "cherry_slab", "display": "Cherry Slab", "icon": "➖"},
    ],
    "Building - Wood Fences & Gates": [
        {"name": "oak_fence", "display": "Oak Fence", "icon": "🚧"},
        {"name": "oak_fence_gate", "display": "Oak Gate", "icon": "🚪"},
        {"name": "spruce_fence", "display": "Spruce Fence", "icon": "🚧"},
        {"name": "spruce_fence_gate", "display": "Spruce Gate", "icon": "🚪"},
        {"name": "birch_fence", "display": "Birch Fence", "icon": "🚧"},
        {"name": "birch_fence_gate", "display": "Birch Gate", "icon": "🚪"},
        {"name": "dark_oak_fence", "display": "Dark Oak Fence", "icon": "🚧"},
        {"name": "dark_oak_fence_gate", "display": "Dark Oak Gate", "icon": "🚪"},
        {"name": "mangrove_fence", "display": "Mangrove Fence", "icon": "🚧"},
        {"name": "mangrove_fence_gate", "display": "Mangrove Gate", "icon": "🚪"},
        {"name": "bamboo_fence", "display": "Bamboo Fence", "icon": "🚧"},
        {"name": "bamboo_fence_gate", "display": "Bamboo Gate", "icon": "🚪"},
        {"name": "crimson_fence", "display": "Crimson Fence", "icon": "🚧"},
        {"name": "crimson_fence_gate", "display": "Crimson Gate", "icon": "🚪"},
        {"name": "warped_fence", "display": "Warped Fence", "icon": "🚧"},
        {"name": "warped_fence_gate", "display": "Warped Gate", "icon": "🚪"},
        {"name": "cherry_fence", "display": "Cherry Fence", "icon": "🚧"},
        {"name": "cherry_fence_gate", "display": "Cherry Gate", "icon": "🚪"},
    ],
    "Building - Stone & Brick Core": [
        {"name": "stone", "display": "Stone", "icon": "🪨"},
        {"name": "smooth_stone", "display": "Smooth Stone", "icon": "⬜"},
        {"name": "cobblestone", "display": "Cobblestone", "icon": "⬛"},
        {"name": "stone_bricks", "display": "Stone Bricks", "icon": "🧱"},
        {"name": "deepslate", "display": "Deepslate", "icon": "⬛"},
        {"name": "polished_deepslate", "display": "Polished Deepslate", "icon": "⬛"},
        {"name": "bricks", "display": "Bricks", "icon": "🧱"},
        {"name": "polished_blackstone_bricks", "display": "Blackstone Bricks", "icon": "⬛"},
        {"name": "basalt", "display": "Basalt", "icon": "⚪"},
        {"name": "sandstone", "display": "Sandstone", "icon": "🟨"},
        {"name": "granite", "display": "Granite", "icon": "🟥"},
        {"name": "diorite", "display": "Diorite", "icon": "⬜"},
        {"name": "andesite", "display": "Andesite", "icon": "⬜"},
        {"name": "blackstone", "display": "Blackstone", "icon": "⬛"},
        {"name": "nether_bricks", "display": "Nether Bricks", "icon": "🟥"},
        {"name": "quartz_block", "display": "Quartz Block", "icon": "⬜"},
        {"name": "deepslate_tiles", "display": "Deepslate Tiles", "icon": "⬛"},
    ],
    "Building - Stone Stairs & Slabs": [
        {"name": "stone_stairs", "display": "Stone Stairs", "icon": "🪜"},
        {"name": "stone_slab", "display": "Stone Slab", "icon": "➖"},
        {"name": "cobblestone_stairs", "display": "Cobbled Stairs", "icon": "🪜"},
        {"name": "cobblestone_slab", "display": "Cobbled Slab", "icon": "➖"},
        {"name": "stone_brick_stairs", "display": "Stone Brick Stairs", "icon": "🪜"},
        {"name": "stone_brick_slab", "display": "Stone Brick Slab", "icon": "➖"},
        {"name": "sandstone_stairs", "display": "Sandstone Stairs", "icon": "🪜"},
        {"name": "sandstone_slab", "display": "Sandstone Slab", "icon": "➖"},
        {"name": "quartz_stairs", "display": "Quartz Stairs", "icon": "🪜"},
        {"name": "quartz_slab", "display": "Quartz Slab", "icon": "➖"},
        {"name": "polished_deepslate_stairs", "display": "Polished Deepslate Stairs", "icon": "🪜"},
        {"name": "polished_deepslate_slab", "display": "Polished Deepslate Slab", "icon": "➖"},
        {"name": "polished_blackstone_brick_stairs", "display": "Blackstone Stairs", "icon": "🪜"},
        {"name": "polished_blackstone_brick_slab", "display": "Blackstone Slab", "icon": "➖"},
        {"name": "deepslate_tile_stairs", "display": "Tile Stairs", "icon": "🪜"},
        {"name": "deepslate_tile_slab", "display": "Tile Slab", "icon": "➖"},
    ],
    "Building - Walls": [
        {"name": "cobblestone_wall", "display": "Cobbled Wall", "icon": "🧱"},
        {"name": "stone_brick_wall", "display": "Stone Brick Wall", "icon": "🧱"},
        {"name": "mossy_stone_brick_wall", "display": "Mossy Brick Wall", "icon": "🌿"},
        {"name": "deepslate_brick_wall", "display": "Deepslate Brick Wall", "icon": "⬛"},
        {"name": "polished_deepslate_wall", "display": "Polished Deepslate Wall", "icon": "⬛"},
        {"name": "blackstone_wall", "display": "Blackstone Wall", "icon": "⬛"},
        {"name": "nether_brick_wall", "display": "Nether Brick Wall", "icon": "🟥"},
    ],
    "Building Materials - Glass & Light": [
        {"name": "glass", "display": "Glass", "icon": "🔲"},
        {"name": "tinted_glass", "display": "Tinted Glass", "icon": "🟪"},
        {"name": "white_stained_glass", "display": "White Glass", "icon": "⬜"},
        {"name": "glass_pane", "display": "Glass Pane", "icon": "〰️"},
        {"name": "white_stained_glass_pane", "display": "White Pane", "icon": "〰️"},
        {"name": "glowstone", "display": "Glowstone", "icon": "✨"},
        {"name": "sea_lantern", "display": "Sea Lantern", "icon": "💡"},
        {"name": "shroomlight", "display": "Shroomlight", "icon": "🟠"},
        {"name": "lantern", "display": "Lantern", "icon": "🏮"},
        {"name": "soul_lantern", "display": "Soul Lantern", "icon": "💙"},
        {"name": "redstone_lamp", "display": "Redstone Lamp", "icon": "💡"},
        {"name": "end_rod", "display": "End Rod", "icon": "🧪"},
    ],

    "Building Materials - Decorative": [
        {"name": "white_concrete", "display": "White Concrete", "icon": "⬜"},
        {"name": "blue_concrete", "display": "Blue Concrete", "icon": "🟦"},
        {"name": "terracotta", "display": "Terracotta", "icon": "🟫"},
        {"name": "white_terracotta", "display": "White Terracotta", "icon": "🤍"},
        {"name": "prismarine", "display": "Prismarine", "icon": "🟩"},
        {"name": "dark_prismarine", "display": "Dark Prismarine", "icon": "🟩"},
        {"name": "polished_basalt", "display": "Polished Basalt", "icon": "⚪"},
    ],
    "Utilities": [
        {"name": "torch", "display": "Torch", "icon": "🔥"},
        {"name": "compass", "display": "Compass", "icon": "🧭"},
        {"name": "map", "display": "Map", "icon": "🗺️"},
        {"name": "spyglass", "display": "Spyglass", "icon": "🔭"},
        {"name": "shield", "display": "Shield", "icon": "🛡️"},
        {"name": "ender_pearl", "display": "Ender Pearl", "icon": "🔮"},
        {"name": "water_bucket", "display": "Water Bucket", "icon": "🪣"},
        {"name": "lava_bucket", "display": "Lava Bucket", "icon": "🪣"},
        {"name": "milk_bucket", "display": "Milk Bucket", "icon": "🥛"},
        {"name": "oak_boat", "display": "Boat", "icon": "⛵"},
        {"name": "bed", "display": "Bed", "icon": "🛏️"},
        {"name": "chest", "display": "Chest", "icon": "📦"},
        {"name": "crafting_table", "display": "Crafting Table", "icon": "🔨"},
        {"name": "furnace", "display": "Furnace", "icon": "🔥"},
        {"name": "anvil", "display": "Anvil", "icon": "⚒️"},
        {"name": "enchanting_table", "display": "Enchanting Table", "icon": "📖"},
        {"name": "ender_chest", "display": "Ender Chest", "icon": "📦"},
        {"name": "shulker_box", "display": "Shulker Box", "icon": "📦"},
        {"name": "campfire", "display": "Campfire", "icon": "🔥"},
        {"name": "hopper", "display": "Hopper", "icon": "🪣"},
        {"name": "observer", "display": "Observer", "icon": "👁️"},
        {"name": "piston", "display": "Piston", "icon": "📦"},
        {"name": "rail", "display": "Rail", "icon": "🛤️"},
        {"name": "lead", "display": "Lead", "icon": "🤝"},
    ],
    "Resources (rare -> common)": [
        {"name": "netherite_ingot", "display": "Netherite Ingot", "icon": "⬛"},
        {"name": "netherite_scrap", "display": "Netherite Scrap", "icon": "⬛"},
        {"name": "ancient_debris", "display": "Ancient Debris", "icon": "🟤"},
        {"name": "diamond", "display": "Diamond", "icon": "💎"},
        {"name": "emerald", "display": "Emerald", "icon": "💚"},
        {"name": "gold_ingot", "display": "Gold Ingot", "icon": "🟡"},
        {"name": "iron_ingot", "display": "Iron Ingot", "icon": "⚪"},
        {"name": "copper_ingot", "display": "Copper Ingot", "icon": "🟠"},
        {"name": "redstone", "display": "Redstone", "icon": "🔴"},
        {"name": "lapis_lazuli", "display": "Lapis Lazuli", "icon": "🔵"},
        {"name": "quartz", "display": "Quartz", "icon": "⬜"},
        {"name": "amethyst_shard", "display": "Amethyst Shard", "icon": "💜"},
        {"name": "raw_gold", "display": "Raw Gold", "icon": "🟡"},
        {"name": "raw_iron", "display": "Raw Iron", "icon": "⚪"},
        {"name": "raw_copper", "display": "Raw Copper", "icon": "🟠"},
        {"name": "coal", "display": "Coal", "icon": "⚫"},
        {"name": "charcoal", "display": "Charcoal", "icon": "⚫"},
        {"name": "slime_ball", "display": "Slime Ball", "icon": "🟢"},
        {"name": "blaze_rod", "display": "Blaze Rod", "icon": "🔥"},
        {"name": "ender_pearl", "display": "Ender Pearl", "icon": "🔮"},
        {"name": "ender_eye", "display": "Eye of Ender", "icon": "👁️"},
        {"name": "ghast_tear", "display": "Ghast Tear", "icon": "💧"},
        {"name": "magma_cream", "display": "Magma Cream", "icon": "🟠"},
        {"name": "phantom_membrane", "display": "Phantom Membrane", "icon": "🪽"},
        {"name": "string", "display": "String", "icon": "🧵"},
        {"name": "gunpowder", "display": "Gunpowder", "icon": "💥"},
    ],
    "Potions & Enchantments": [
        {"name": "potion{Potion:\"minecraft:healing\"}", "display": "Healing Potion", "icon": "❤️"},
        {"name": "potion{Potion:\"minecraft:strong_healing\"}", "display": "Strong Healing", "icon": "💗"},
        {"name": "potion{Potion:\"minecraft:regeneration\"}", "display": "Regeneration", "icon": "💚"},
        {"name": "potion{Potion:\"minecraft:swiftness\"}", "display": "Swiftness", "icon": "💨"},
        {"name": "potion{Potion:\"minecraft:strength\"}", "display": "Strength", "icon": "💪"},
        {"name": "potion{Potion:\"minecraft:fire_resistance\"}", "display": "Fire Resistance", "icon": "🔥"},
        {"name": "potion{Potion:\"minecraft:night_vision\"}", "display": "Night Vision", "icon": "👁️"},
        {"name": "enchanted_book", "display": "Enchanted Book", "icon": "📕"},
        {"name": "experience_bottle", "display": "XP Bottle", "icon": "✨"},
        {"name": "potion{Potion:\"minecraft:slow_falling\"}", "display": "Slow Falling", "icon": "🪽"},
        {"name": "potion{Potion:\"minecraft:water_breathing\"}", "display": "Water Breathing", "icon": "💧"},
        {"name": "potion{Potion:\"minecraft:leaping\"}", "display": "Jump Boost", "icon": "🦘"},
        {"name": "potion{Potion:\"minecraft:turtle_master\"}", "display": "Turtle Master", "icon": "🐢"},
    ],
    "Special": [
        {"name": "totem_of_undying", "display": "Totem of Undying", "icon": "✨"},
        {"name": "nether_star", "display": "Nether Star", "icon": "⭐"},
        {"name": "dragon_egg", "display": "Dragon Egg", "icon": "🥚"},
        {"name": "beacon", "display": "Beacon", "icon": "🔆"},
        {"name": "conduit", "display": "Conduit", "icon": "💠"},
        {"name": "heart_of_the_sea", "display": "Heart of the Sea", "icon": "💙"},
        {"name": "music_disc_cat", "display": "Music Disc", "icon": "💿"},
        {"name": "saddle", "display": "Saddle", "icon": "🏇"},
        {"name": "name_tag", "display": "Name Tag", "icon": "🏷️"},
        {"name": "elytra", "display": "Elytra", "icon": "🪽"},
        {"name": "goat_horn", "display": "Goat Horn", "icon": "📯"},
    ],
    "Arrows & Ammo": [
        {"name": "arrow", "display": "Arrow", "icon": "➡️"},
        {"name": "spectral_arrow", "display": "Spectral Arrow", "icon": "✨"},
        {"name": "tipped_arrow{Potion:\"minecraft:poison\"}", "display": "Poison Arrow", "icon": "☠️"},
        {"name": "firework_rocket", "display": "Firework", "icon": "🎆"},
        {"name": "tipped_arrow{Potion:\"minecraft:slow_falling\"}", "display": "Slow Falling Arrow", "icon": "🪽"},
        {"name": "tipped_arrow{Potion:\"minecraft:weakness\"}", "display": "Weakness Arrow", "icon": "💤"},
    ],
}
