PRESETS = {
    "base": "392 61 297",
    "village1": "-1360 70 637",
    "village2": "-3777 63 3823",
    "ice_area": "427 85 -39",
}

VILLAGE_TYPES = [
    "plains",
    "desert",
    "savanna",
    "taiga",
    "snowy"
]

ITEMS = {
    "Food": [
        {"name": "cooked_beef", "display": "Cooked Beef", "icon": "🥩"},
        {"name": "golden_carrot", "display": "Golden Carrot", "icon": "🥕"},
        {"name": "bread", "display": "Bread", "icon": "🍞"},
        {"name": "cooked_porkchop", "display": "Cooked Porkchop", "icon": "🍖"},
        {"name": "cooked_chicken", "display": "Cooked Chicken", "icon": "🍗"},
        {"name": "cooked_mutton", "display": "Cooked Mutton", "icon": "🥩"},
        {"name": "baked_potato", "display": "Baked Potato", "icon": "🥔"},
        {"name": "golden_apple", "display": "Golden Apple", "icon": "🍎"},
        {"name": "enchanted_golden_apple", "display": "God Apple", "icon": "✨"},
    ],
    "Tools & Weapons": [
        {"name": "diamond_pickaxe", "display": "Diamond Pickaxe", "icon": "⛏️"},
        {"name": "diamond_axe", "display": "Diamond Axe", "icon": "🪓"},
        {"name": "diamond_shovel", "display": "Diamond Shovel", "icon": "🔨"},
        {"name": "diamond_sword", "display": "Diamond Sword", "icon": "⚔️"},
        {"name": "diamond_hoe", "display": "Diamond Hoe", "icon": "🔧"},
        {"name": "netherite_pickaxe", "display": "Netherite Pickaxe", "icon": "⛏️"},
        {"name": "netherite_axe", "display": "Netherite Axe", "icon": "🪓"},
        {"name": "netherite_sword", "display": "Netherite Sword", "icon": "⚔️"},
        {"name": "bow", "display": "Bow", "icon": "🏹"},
        {"name": "crossbow", "display": "Crossbow", "icon": "🏹"},
        {"name": "trident", "display": "Trident", "icon": "🔱"},
        {"name": "fishing_rod", "display": "Fishing Rod", "icon": "🎣"},
        {"name": "shears", "display": "Shears", "icon": "✂️"},
    ],
    "Armor": [
        {"name": "diamond_helmet", "display": "Diamond Helmet", "icon": "⛑️"},
        {"name": "diamond_chestplate", "display": "Diamond Chestplate", "icon": "🦺"},
        {"name": "diamond_leggings", "display": "Diamond Leggings", "icon": "👖"},
        {"name": "diamond_boots", "display": "Diamond Boots", "icon": "👢"},
        {"name": "netherite_helmet", "display": "Netherite Helmet", "icon": "⛑️"},
        {"name": "netherite_chestplate", "display": "Netherite Chestplate", "icon": "🦺"},
        {"name": "netherite_leggings", "display": "Netherite Leggings", "icon": "👖"},
        {"name": "netherite_boots", "display": "Netherite Boots", "icon": "👢"},
        {"name": "elytra", "display": "Elytra", "icon": "🪽"},
    ],
    "Building Materials": [
        {"name": "stone", "display": "Stone", "icon": "🪨"},
        {"name": "oak_planks", "display": "Oak Planks", "icon": "🪵"},
        {"name": "glass", "display": "Glass", "icon": "🔲"},
        {"name": "cobblestone", "display": "Cobblestone", "icon": "⬛"},
        {"name": "dirt", "display": "Dirt", "icon": "🟤"},
        {"name": "sand", "display": "Sand", "icon": "🟨"},
        {"name": "oak_log", "display": "Oak Log", "icon": "🪵"},
        {"name": "white_wool", "display": "White Wool", "icon": "⬜"},
        {"name": "bricks", "display": "Bricks", "icon": "🧱"},
    ],
    "Utilities": [
        {"name": "torch", "display": "Torch", "icon": "🔥"},
        {"name": "compass", "display": "Compass", "icon": "🧭"},
        {"name": "map", "display": "Map", "icon": "🗺️"},
        {"name": "spyglass", "display": "Spyglass", "icon": "🔭"},
        {"name": "shield", "display": "Shield", "icon": "🛡️"},
        {"name": "ender_pearl", "display": "Ender Pearl", "icon": "🔮"},
        {"name": "water_bucket", "display": "Water Bucket", "icon": "🪣"},
        {"name": "lava_bucket", "display": "Lava Bucket", "icon": "🪣"},
        {"name": "milk_bucket", "display": "Milk Bucket", "icon": "🥛"},
        {"name": "oak_boat", "display": "Boat", "icon": "⛵"},
        {"name": "bed", "display": "Bed", "icon": "🛏️"},
        {"name": "chest", "display": "Chest", "icon": "📦"},
        {"name": "crafting_table", "display": "Crafting Table", "icon": "🔨"},
        {"name": "furnace", "display": "Furnace", "icon": "🔥"},
        {"name": "anvil", "display": "Anvil", "icon": "⚒️"},
        {"name": "enchanting_table", "display": "Enchanting Table", "icon": "📖"},
        {"name": "ender_chest", "display": "Ender Chest", "icon": "📦"},
        {"name": "shulker_box", "display": "Shulker Box", "icon": "📦"},
        {"name": "campfire", "display": "Campfire", "icon": "🔥"},
        {"name": "lantern", "display": "Lantern", "icon": "🏮"},
        {"name": "soul_lantern", "display": "Soul Lantern", "icon": "💙"},
    ],
    "Resources": [
        {"name": "coal", "display": "Coal", "icon": "⚫"},
        {"name": "raw_copper", "display": "Raw Copper", "icon": "🟠"},
        {"name": "raw_iron", "display": "Raw Iron", "icon": "⚪"},
        {"name": "raw_gold", "display": "Raw Gold", "icon": "🟡"},
        {"name": "iron_ingot", "display": "Iron Ingot", "icon": "⚪"},
        {"name": "gold_ingot", "display": "Gold Ingot", "icon": "🟡"},
        {"name": "diamond", "display": "Diamond", "icon": "💎"},
        {"name": "emerald", "display": "Emerald", "icon": "💚"},
        {"name": "netherite_ingot", "display": "Netherite Ingot", "icon": "⬛"},
        {"name": "redstone", "display": "Redstone", "icon": "🔴"},
        {"name": "lapis_lazuli", "display": "Lapis Lazuli", "icon": "🔵"},
        {"name": "quartz", "display": "Quartz", "icon": "⬜"},
        {"name": "ancient_debris", "display": "Ancient Debris", "icon": "🟤"},
    ],
    "Potions & Enchantments": [
        {"name": "potion{Potion:\"minecraft:healing\"}", "display": "Healing Potion", "icon": "❤️"},
        {"name": "potion{Potion:\"minecraft:strong_healing\"}", "display": "Strong Healing", "icon": "💗"},
        {"name": "potion{Potion:\"minecraft:regeneration\"}", "display": "Regeneration", "icon": "💚"},
        {"name": "potion{Potion:\"minecraft:swiftness\"}", "display": "Swiftness", "icon": "💨"},
        {"name": "potion{Potion:\"minecraft:strength\"}", "display": "Strength", "icon": "💪"},
        {"name": "potion{Potion:\"minecraft:fire_resistance\"}", "display": "Fire Resistance", "icon": "🔥"},
        {"name": "potion{Potion:\"minecraft:night_vision\"}", "display": "Night Vision", "icon": "👁️"},
        {"name": "enchanted_book", "display": "Enchanted Book", "icon": "📕"},
        {"name": "experience_bottle", "display": "XP Bottle", "icon": "✨"},
    ],
    "Special": [
        {"name": "totem_of_undying", "display": "Totem of Undying", "icon": "✨"},
        {"name": "nether_star", "display": "Nether Star", "icon": "⭐"},
        {"name": "dragon_egg", "display": "Dragon Egg", "icon": "🥚"},
        {"name": "beacon", "display": "Beacon", "icon": "🔆"},
        {"name": "conduit", "display": "Conduit", "icon": "💠"},
        {"name": "heart_of_the_sea", "display": "Heart of the Sea", "icon": "💙"},
        {"name": "music_disc_cat", "display": "Music Disc", "icon": "💿"},
        {"name": "saddle", "display": "Saddle", "icon": "🏇"},
        {"name": "name_tag", "display": "Name Tag", "icon": "🏷️"},
    ],
    "Arrows & Ammo": [
        {"name": "arrow", "display": "Arrow", "icon": "➡️"},
        {"name": "spectral_arrow", "display": "Spectral Arrow", "icon": "✨"},
        {"name": "tipped_arrow{Potion:\"minecraft:poison\"}", "display": "Poison Arrow", "icon": "☠️"},
        {"name": "firework_rocket", "display": "Firework", "icon": "🎆"},
    ]
}
